### ISSUE TITLE
Status Solar circuit wrong / Pump status Solar & Buffer storage in %

### ISSUE THREAD

**Issue by WahlFisch91** [dominikamann/oekofen-pellematic-compact#58]
Hi,
I have noticed, when the Solar deliveres heat, the Status of the Circuit (in my case "sk3.L_statetext") in the HTTP Api switches to null, instead of showing for example "solar active" - So in Homeassistant, the satus says "unknown" when active.

The Pump status of the solar pump and the buffer storage pump (in my case "sk3.L_pump" & "pu1.L_pump") is delivered as % from the HTTP Api (0-100%). This happens, because the pumps are PWM controlled (in my case - or maybe general).
In Homeassistant, it shows only 0 when the pump is in idle, and "unknown" when the pump is active.

**Comment by lucaferrucci** [comment]
Hi Dominik, with the latest update this morning the integrations created for the energy panel blocked the settings, I think your update is necessary, the problem is that with 2024/7 it is not possible to enter the panel settings to temporarily delete them, you have to revert back to the previous version of Hass and take action

**Comment by dominikamann** [comment]
Can you please share the json with the values / situations? Thanks!

**Comment by WahlFisch91** [comment]
{
 "sk3":{
  "L_koll_temp":700, 
  "L_spu":574, 
  **"L_pump":78,** 
  "L_state":0, 
  **"L_statetext":"",**
  "mode":1, 
  "cooling":0, 
  "spu_max":800, 
  "name":"Solar"
 }
}
____________________________________________________________
{
 "pu1":{
  "L_tpo_act":611, 
  "L_tpo_set":300, 
  "L_tpm_act":606, 
  "L_tpm_set":300, 
  "L_pump_release":80, 
  "L_pump":50, 
  "L_state":512, 
  "L_statetext":"Anforderung Aus",
  "mintemp_off":300, 
  "mintemp_on":300, 
  "ext_mintemp_off":80, 
  "ext_mintemp_on":80
 }
}




The "Pump" values above are measured in % (100% is full pump speed)

At the moment, the solar is delivering - you can see that above (pump speed = 78%)
As i already described, when solar is delivering, the statetext is blank. Only if the Solar is inactive ( lets say, because of temperature), the datapoint gives some status message...

**Comment by dominikamann** [comment]
Okay, regarding the "Pump" issue, the entities were added as Binary Sensors ("on" / "off"). In my case, that's valid, but it seems to be invalid in your case.

![grafik](https://github.com/dominikamann/oekofen-pellematic-compact/assets/29973737/d37c3035-9cec-4a23-8fab-18ae9eb317bf)

I think it might be possible to add all the pump sensors in both formats (as binary and as numeric/percentage), so everyone can choose the entity in Home Assistant that fits their system. Alternatively, it could be configurable, but I think that might get too complex/complicated.

I will try that out.

**Comment by lucaferrucci** [comment]
Hi, what software version do you have in your boiler?

**Comment by WahlFisch91** [comment]
Hi Luca,

My version is "Touch V4.02b"

greets

**Comment by lucaferrucci** [comment]
ah, ok, it’s right

**Comment by dominikamann** [comment]
@WahlFisch91 Please check https://github.com/dominikamann/oekofen-pellematic-compact/releases/tag/v3.3.2

**Comment by WahlFisch91** [comment]
works perfectly - thanks a lot!
 

Mit freundlichen Grüßen,
best regards,

Wolfgang Wahl

 
 

Gesendet: Mittwoch, 07. August 2024 um 12:18 Uhr
Von: "Dominik Amann" ***@***.***>
An: "dominikamann/oekofen-pellematic-compact" ***@***.***>
Cc: "WahlFisch91" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [dominikamann/oekofen-pellematic-compact] Status Solar circuit wrong / Pump status Solar & Buffer storage in % (Issue #58)


 

@WahlFisch91 Please check https://github.com/dominikamann/oekofen-pellematic-compact/releases/tag/v3.3.2

**Comment by Jamjon** [comment]
The pump is now working for me, but the Status is empty 
![image](https://github.com/user-attachments/assets/fe45e80c-9367-499c-87b5-2be14d6d11ea)
should this also work now or is it also still broken on your side?

**Comment by WahlFisch91** [comment]
@Jamjon you are right! - did not checked that when i was testing - sorry

The problem is, that the pellematic HTTP API does send an empty field in the "statetext" variable when the solar is delivering heat.
The field statetext contains text, when no heat is delivered from the solar circuit.

@dominikamann can you check that again?

**Comment by dominikamann** [comment]
Hi,

"I have noticed, when the Solar deliveres heat, the Status of the Circuit (in my case "sk3.L_statetext") in the HTTP Api switches to null, instead of showing for example "solar active" - So in Homeassistant, the satus says "unknown" when active."

I would suggest to solve this issue with an Helper (see https://www.home-assistant.io/integrations/template/). Because my integration is just reading what the Ökofen-Heater delivers. If I add custom logic it may breaks with a new version. 

Settings -> Devices -> Helpers

![image](https://github.com/user-attachments/assets/f7035a11-9478-4c6a-bd33-b58ea4a8efe0)


![image](https://github.com/user-attachments/assets/762109ed-06f5-4105-ad67-7985a7a1144c)
